package docs:adder@0.1.0;

interface add {
    record person {
        age: u32,
    }

    add: func(x: u64, y: u64) -> u64;
    greet: func(name: string) -> string;
    show-person: func(p: person) -> u32;

}



world adder {
    export add;
}

